version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
    depends_on:
      - redis

  redis:
    image: redis:6
    command: redis-server --requirepass your_redis_password
    ports:
      - "6379:6379"
